#!/bin/bash
# am ersten Samstag im Monat wird ein full backup gemacht, 
# an anderen Samstagen ein diff backup
# Frank Schütte 2014
# cal hat ein strenges Format, wobei Leerzeichen verwendet werden.
# cal -h hebt den aktuellen Tag nicht hervor.

when=`cal -h | head -n 3 | tail -n 1 |cut -c 19-20`
now=`date "+%_d"`
echo -n "when:$when|now:$now|equal?:"
[ $when -eq $now ] && echo true || echo false

if [ $when -eq $now ]; then
        echo "doing oss-mondobackup --full"
        /usr/sbin/oss-mondobackup --full
else
        echo "doing oss-mondobackup --diff."
        /usr/sbin/oss-mondobackup --diff
fi

