#!/bin/bash
# am ersten Samstag im Monat wird ein full backup gemacht, 
# an anderen Samstagen ein diff backup
# Frank Schütte 2017
# cal hat ein strenges Format, wobei Leerzeichen verwendet werden.

when=`cal | head -n 3 | tail -n 1 |cut -c 19-20`
now=`date "+%_d"`
echo -n "when:$when|now:$now|equal?:"
[ $when -eq $now ] && echo true || echo false

if [ $when -eq $now ]; then
        echo "doing oss-mondobackup -f[ull]."
        /sbin/oss-mondobackup -f
else
        echo "doing oss-mondobackup -d[iff]."
        /sbin/oss-mondobackup -d
fi

