#!/bin/bash
# am ersten Samstag im Monat wird ein full backup gemacht, 
# an anderen Samstagen ein diff backup
# Frank Schütte 2017
# cal hat ein strenges Format, wobei Leerzeichen verwendet werden.

when=`/usr/bin/cal | /usr/bin/head -n 3 | /usr/bin/tail -n 1 |/usr/bin/cut -c 16-17`
now=`/usr/bin/date "+%_d"`
/usr/bin/echo -n "when:$when|now:$now|equal?:"
[ $when -eq $now ] && /ur/bin/echo true || /usr/bin/echo false

if [ $when -eq $now ]; then
        echo "doing oss-mondobackup -f[ull]."
        /sbin/oss-mondobackup -f
else
        echo "doing oss-mondobackup -d[iff]."
        /sbin/oss-mondobackup -d
fi

